version: 2.1
anchors:
  env_gradle: &env_gradle
    environment:
       # we're only allowed to use 2 vCPUs
      GRADLE_OPTS: "-Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:8.0

  restore_cache_wrapper: &restore_cache_wrapper
    restore_cache:
      key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  restore_cache_deps: &restore_cache_deps
    restore_cache:
      keys:
        - gradle-deps-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
        - gradle-deps-
  set_git_origin_to_https: &set_git_origin_to_https
    run:
      name: set git origin to https
      command: git remote set-url --push origin https://github.com/diffplug/atplug

jobs:
  test_8: 
    <<: *env_gradle
    steps:
      - checkout
      - run:
          name: gradlew test
          command: ./gradlew test
      - run:
          name: gradlew javadoc
          command: ./gradlew javadoc
      - store_test_results:
          path: build/test-results/test
  test_11: 
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: gradlew test
          command: ./gradlew test
      - run:
          name: gradlew spotlessCheck
          command: ./gradlew spotlessCheck
      - store_test_results:
          path: build/test-results/test
  changelog_print:
    << : *env_gradle
    steps:
      - checkout
      - *restore_cache_wrapper
      - *restore_cache_deps
      - run:
          name: gradlew changelogPrint
          command: ./gradlew changelogPrint
  do_release:
    << : *env_gradle
    steps:
      - checkout
      - *restore_cache_wrapper
      - *restore_cache_deps
      - *set_git_origin_to_https
      - run:
          name: changelogPush
          command: ./gradlew changelogPush -Penable_publishing=true -Pgradle.publish.key=${gradle_key} -Pgradle.publish.secret=${gradle_secret} --stacktrace --warning-mode all

workflows:
  version: 2
  tests:
    jobs:
    - test_8
    - test_11
  deploy:
    jobs:
      - changelog_print:
          filters:
            branches:
              only: main
      - release:
          type: approval
          requires:
            - changelog_print
      - do_release:
          requires:
            - release
          context:
            - SonatypeDeploy
