name: "Validate Gradle Wrapper"
on:
  push:
    paths:
      - 'gradlew'
      - 'gradlew.bat'
      - 'gradle/wrapper/'
  pull_request:
    paths:
      - 'gradlew'
      - 'gradlew.bat'
      - 'gradle/wrapper/'

permissions:
  contents: read

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
